name: Script checks
on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - 'scripts/**'
jobs:
    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: if [ -n "$ACT" ]; then sudo apt update && sudo apt -y install shellcheck; fi
            - run: cd scripts && shellcheck ./**
